### ISSUE TITLE
Missing used fonts

### ISSUE THREAD

**Issue by FDiskas** [drahosp/dotfiles#1]
![image](https://user-images.githubusercontent.com/468006/65043100-ee53c300-d962-11e9-8046-3096b11017be.png)

https://github.com/drahosp/dotfiles/blob/e9ea47ed25d42cdab7a34c8ca1c6edb117cf56e3/zshrc#L57

**Comment by drahosp** [comment]
Hey, the fonts I use are included in the fonts subdirectory. You can however use any font from https://www.nerdfonts.com
